#!/bin/bash

# Submit job scripts generated by fsl_randomise_imgs.sh

# /network/iss/cenir/analyse/irm/users/martin.johansson/code/iceberg/rsfmri_fc/fsl_randomise_jobsub.sh
# rm -r /network/iss/cenir/analyse/irm/users/martin.johansson/iceberg/stats/fc_seed_based/derivatives/randomise/seed-*/g0*/*
# rm -r /network/iss/cenir/analyse/irm/users/martin.johansson/iceberg/stats/fc_seed_based/derivatives/randomise/seed-*/g0*/vals

statsdir="/network/iss/cenir/analyse/irm/users/martin.johansson/iceberg/stats/fc_seed_based/derivatives/randomise"
logsdir="/network/iss/cenir/analyse/irm/users/martin.johansson/iceberg/stats/fc_seed_based/derivatives/randomise/logs"
seed=("PP" "PA" "PAsubPP")
#seed=("CB12" "CB56" "CB56subCB12" "PP" "PA" "PAsubPP")
ses=("V0" "V2" "V4")
group_comparison="*"
for(( i=0; i<${#seed[@]}; i++ )); do
 for(( j=0; j<${#ses[@]}; j++ )); do
  rand_dir=${statsdir}/seed-${seed[i]}_ses-${ses[j]}
  jobscripts=( $(ls ${rand_dir}/cmd__${group_comparison}.txt) )
   for(( k=0; k<${#jobscripts[@]}; k++ )); do

   echo ">>> Submitting seed: ${seed[i]}, session: ${ses[j]}"
   JNAME=`basename -- "${jobscripts[k]}" .txt`
			
   sbatch \
    --output ${logsdir}/job.rand.%A_%a.out \
    --error ${logsdir}/job.rand.%A_%a.err \
    --job-name "rand_${seed[i]}_${ses[j]}_${JNAME}" \
    --nodes=1 --cpus-per-task 2 --ntasks-per-node=1 --mem=8G --time=06:00:00 --exclude=sphpc-cpu20 \
    ${jobscripts[k]}	

   done
 done
done
